"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Calendar, TrendingUp, Sparkles } from "lucide-react"
import type { Task } from "@/lib/mock-data"
import { format } from "date-fns"

interface EmployeeInsightsProps {
  insights: string
  tasks: Task[]
}

export function EmployeeInsights({ insights, tasks }: EmployeeInsightsProps) {
  const today = format(new Date(), "yyyy-MM-dd")
  const todayTasks = tasks.filter((t) => t.date === today)

  const statusCounts = tasks.reduce(
    (acc, task) => {
      acc[task.status]++
      return acc
    },
    { planned: 0, done: 0, blocked: 0 } as Record<Task["status"], number>,
  )

  return (
    <div className="grid gap-6 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Calendar className="h-5 w-5" />
            Today's Focus
          </CardTitle>
          <CardDescription>Your tasks for today</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Tasks today</span>
              <span className="text-2xl font-bold">{todayTasks.length}</span>
            </div>
            {todayTasks.length > 0 ? (
              <div className="space-y-2">
                {todayTasks.map((task) => (
                  <div key={task.id} className="rounded-md border p-2 text-sm">
                    <div className="font-medium">{task.title}</div>
                    <div className="text-xs text-muted-foreground capitalize">{task.status}</div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">No tasks scheduled for today</p>
            )}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5" />
            Overall Progress
          </CardTitle>
          <CardDescription>Your task completion summary</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm">Completed</span>
                <span className="font-semibold text-[var(--status-done)]">{statusCounts.done}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-sm">Planned</span>
                <span className="font-semibold text-[var(--status-planned)]">{statusCounts.planned}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-sm">Blocked</span>
                <span className="font-semibold text-[var(--status-blocked)]">{statusCounts.blocked}</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="md:col-span-2">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            AI Analysis
          </CardTitle>
          <CardDescription>Personalized insights generated by AI</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="prose prose-sm max-w-none">
            <p className="whitespace-pre-wrap text-sm leading-relaxed">{insights}</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
